### ISSUE TITLE
Establish visual design style guide in connection with PR Self-Review Checklist

### ISSUE THREAD

**Issue by audreyfeldroy** [margaritahumanitarian/helpafamily#261]
This issue is about use of consistent visual styles throughout the helpafamily codebase, such as color palette, button design, and other visual uses of CSS.

- [x] Create a Visual Design Style Guide doc in https://app.gitbook.com/@margaritahumanitarian/s/help-a-family-manual/contributing-to-the-repository
- [x] Add 1 or more checklist items to connect the style guidelines with the Self-Review Checklist
- [x] Implement use of styled jsx library in style guide
  - [x] Document examples of what to do vs. what not to do

I'm assigning this to @LowLifeArcade as one of his leadership tasks as our Lead Software Engineer on this project. Really excited to be working with you @LowLifeArcade 😄
